//////////////////////////////////////////////////////////
// This class has been automatically generated on
// Tue Oct 12 12:20:57 2010 by ROOT version 5.22/00d
// from TTree t/t
// found on file: /storage/5/jyothsna/btag_18Sep_QCDPt80/standardPFNtuple_1_2_pIs.root
//////////////////////////////////////////////////////////

#ifndef MuonSelector_h
#define MuonSelector_h

#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>
#include <TSelector.h>
#include <iostream>
#include "informationMuonCuts.h"
#include "TH1D.h"

class MuonSelector : public TSelector {
public :
   TTree          *fChain;   //!pointer to the analyzed TTree or TChain

  // some objects
   TH1D* dataHist;
   TH1D* mcHistb;
   TH1D* mcHistbglusplit;
   TH1D* mcHistc; 
   TH1D* mcHistl;
   TH1D* mcHistn;
   bool  isData;
   informationMuonCuts info;


   // Declaration of leaf types
   Bool_t          triggerHLTL1Jet6U;
   Bool_t          triggerHLTL1Jet10U;
   Bool_t          triggerHLTJet15U;
   Bool_t          triggerHLTJet30U;
   Bool_t          triggerHLTJet50U;
   Bool_t          triggerHLTJet70U;
   Bool_t          triggerHLTJet100U;
   Bool_t          isGluonSplitting;
   UInt_t          eventNumber;
   UInt_t          runNumber;
   UInt_t          lumiBlockNumber;
   UInt_t          numberOfPrimaryVertices;
   Float_t         pthat;
   Int_t           nJets;
   Float_t         jetPt[40];   //[nJets]
   Float_t         jetEta[40];   //[nJets]
   Float_t         jetPhi[40];   //[nJets]
   Float_t         jetEMFraction[40];   //[nJets]
   Float_t         jetChargedEmEnergyFraction[40];   //[nJets]
   Float_t         jetNeutralEmEnergyFraction[40];   //[nJets]
   Float_t         jetChargedHadronEnergyFraction[40];   //[nJets]
   Float_t         jetNeutralHadronEnergyFraction[40];   //[nJets]
   Float_t         jetChargedMultiplicity[40];   //[nJets]
   Float_t         jetMass[40];   //[nJets]
   Int_t           jetnConstituents[40];   //[nJets]
   Int_t           jetnTracks[40];   //[nJets]
   Float_t         jetVertexChi2[40];   //[nJets]
   Float_t         jetVertexChi2Ndof[40];   //[nJets]
   Float_t         jetVertexNormalizedChi2[40];   //[nJets]
   Int_t           nTracks;
   Int_t           trackJetIndex[300];   //[nTracks]
   Bool_t          trackSelected[300];   //[nTracks]
   Float_t         trackTransverseMomentum[300];   //[nTracks]
   Float_t         trackEta[300];   //[nTracks]
   Float_t         trackPhi[300];   //[nTracks]
   Float_t         trackMomentum[300];   //[nTracks]
   Int_t           trackNHits[300];   //[nTracks]
   Int_t           trackNPixelHits[300];   //[nTracks]
   Float_t         trackChi2[300];   //[nTracks]
   Float_t         trackNormChi2[300];   //[nTracks]
   Int_t           trackQuality[300];   //[nTracks]
   Float_t         trackLongitudinalImpactParameter[300];   //[nTracks]
   Float_t         trackIP[300];   //[nTracks]
   Float_t         trackDecayLength[300];   //[nTracks]
   Float_t         trackDistJetAxis[300];   //[nTracks]
   Float_t         trackDeltaR[300];   //[nTracks]
   Float_t         trackIP3d[300];   //[nTracks]
   Float_t         trackIP2d[300];   //[nTracks]
   Float_t         trackIP3dError[300];   //[nTracks]
   Float_t         trackIP2dError[300];   //[nTracks]
   Int_t           trackHasSharedPix1[300];   //[nTracks]
   Int_t           trackHasSharedPix2[300];   //[nTracks]
   Int_t           trackHasSharedPix3[300];   //[nTracks]
   Int_t           trackHasSharedPixAll[300];   //[nTracks]
   Int_t           MCTrueFlavor[40];   //[nJets]
   Float_t         SV3dDistance[40];   //[nJets]
   Float_t         SV3dDistanceError[40];   //[nJets]
   Float_t         SV2dDistance[40];   //[nJets]
   Float_t         SV2dDistanceError[40];   //[nJets]
   Float_t         SVChi2[40];   //[nJets]
   Float_t         SVIPFirstAboveCharm[40];   //[nJets]
   Float_t         SVDegreesOfFreedom[40];   //[nJets]
   Float_t         SVNormChi2[40];   //[nJets]
   Int_t           SVnSelectedTracks[40];   //[nJets]
   Float_t         SVMass[40];   //[nJets]
   Float_t         SVEnergyRatio[40];   //[nJets]
   Int_t           SVnVertices[40];   //[nJets]
   Int_t           SVnVertexTracks[40];   //[nJets]
   Int_t           SVnVertexTracksAll[40];   //[nJets]
   Int_t           SVnFirstVertexTracks[40];   //[nJets]
   Int_t           SVnFirstVertexTracksAll[40];   //[nJets]
   Float_t         SVjetDeltaR[40];   //[nJets]
   Float_t         SVvtxSumVtxDirDeltaR[40];   //[nJets]
   Float_t         SVvtxSumJetDeltaR[40];   //[nJets]
   Int_t           IPnSelectedTracks[40];   //[nJets]
   Float_t         IPghostTrackPt[40];   //[nJets]
   Float_t         IPghostTrackPtRel[40];   //[nJets]
   Float_t         IPghostTrackEta[40];   //[nJets]
   Float_t         IPghostTrackPhi[40];   //[nJets]
   Float_t         IPghostTrackDeltaR[40];   //[nJets]
   Int_t           IPPix1SharedHits[40];   //[nJets]
   Int_t           IPPix1TotalHits[40];   //[nJets]
   Int_t           IPPix2SharedHits[40];   //[nJets]
   Int_t           IPPix2TotalHits[40];   //[nJets]
   Int_t           IPPix3SharedHits[40];   //[nJets]
   Int_t           IPPix3TotalHits[40];   //[nJets]
   Int_t           IPPixAllSharedHits[40];   //[nJets]
   Int_t           IPPixAllTotalHits[40];   //[nJets]
   Int_t           IP3dTrackQuality1[40];   //[nJets]
   Int_t           IP3dHasSharedPix11[40];   //[nJets]
   Int_t           IP3dHasSharedPix21[40];   //[nJets]
   Int_t           IP3dHasSharedPix31[40];   //[nJets]
   Int_t           IP3dHasSharedPixAll1[40];   //[nJets]
   Float_t         IP3d1[40];   //[nJets]
   Float_t         IP3dError1[40];   //[nJets]
   Float_t         IP3dProbability1[40];   //[nJets]
   Float_t         IP3dTrackPtRel1[40];   //[nJets]
   Float_t         IP3dDistJetAxis1[40];   //[nJets]
   Float_t         IP3dDecayLength1[40];   //[nJets]
   Float_t         IP3dDeltaR1[40];   //[nJets]
   Float_t         IP3dMomentum1[40];   //[nJets]
   Float_t         IP3dTransverseMomentum1[40];   //[nJets]
   Float_t         IP3dEta1[40];   //[nJets]
   Float_t         IP3dPhi1[40];   //[nJets]
   Int_t           IP3dNHits1[40];   //[nJets]
   Int_t           IP3dNPixelHits1[40];   //[nJets]
   Float_t         IP3dNormChi21[40];   //[nJets]
   Int_t           IP2dTrackQuality1[40];   //[nJets]
   Float_t         IP2d1[40];   //[nJets]
   Float_t         IP2dError1[40];   //[nJets]
   Float_t         IP2dProbability1[40];   //[nJets]
   Float_t         IP2dTrackPtRel1[40];   //[nJets]
   Int_t           IP3dTrackQuality2[40];   //[nJets]
   Int_t           IP3dHasSharedPix12[40];   //[nJets]
   Int_t           IP3dHasSharedPix22[40];   //[nJets]
   Int_t           IP3dHasSharedPix32[40];   //[nJets]
   Int_t           IP3dHasSharedPixAll2[40];   //[nJets]
   Float_t         IP3d2[40];   //[nJets]
   Float_t         IP3dError2[40];   //[nJets]
   Float_t         IP3dProbability2[40];   //[nJets]
   Float_t         IP3dTrackPtRel2[40];   //[nJets]
   Float_t         IP3dDistJetAxis2[40];   //[nJets]
   Float_t         IP3dDecayLength2[40];   //[nJets]
   Float_t         IP3dDeltaR2[40];   //[nJets]
   Float_t         IP3dMomentum2[40];   //[nJets]
   Float_t         IP3dTransverseMomentum2[40];   //[nJets]
   Float_t         IP3dEta2[40];   //[nJets]
   Float_t         IP3dPhi2[40];   //[nJets]
   Int_t           IP3dNHits2[40];   //[nJets]
   Int_t           IP3dNPixelHits2[40];   //[nJets]
   Float_t         IP3dNormChi22[40];   //[nJets]
   Int_t           IP2dTrackQuality2[40];   //[nJets]
   Float_t         IP2d2[40];   //[nJets]
   Float_t         IP2dError2[40];   //[nJets]
   Float_t         IP2dProbability2[40];   //[nJets]
   Float_t         IP2dTrackPtRel2[40];   //[nJets]
   Int_t           IP3dTrackQuality3[40];   //[nJets]
   Int_t           IP3dHasSharedPix13[40];   //[nJets]
   Int_t           IP3dHasSharedPix23[40];   //[nJets]
   Int_t           IP3dHasSharedPix33[40];   //[nJets]
   Int_t           IP3dHasSharedPixAll3[40];   //[nJets]
   Float_t         IP3d3[40];   //[nJets]
   Float_t         IP3dError3[40];   //[nJets]
   Float_t         IP3dProbability3[40];   //[nJets]
   Float_t         IP3dTrackPtRel3[40];   //[nJets]
   Float_t         IP3dDistJetAxis3[40];   //[nJets]
   Float_t         IP3dDecayLength3[40];   //[nJets]
   Float_t         IP3dDeltaR3[40];   //[nJets]
   Float_t         IP3dMomentum3[40];   //[nJets]
   Float_t         IP3dTransverseMomentum3[40];   //[nJets]
   Float_t         IP3dEta3[40];   //[nJets]
   Float_t         IP3dPhi3[40];   //[nJets]
   Int_t           IP3dNHits3[40];   //[nJets]
   Int_t           IP3dNPixelHits3[40];   //[nJets]
   Float_t         IP3dNormChi23[40];   //[nJets]
   Int_t           IP2dTrackQuality3[40];   //[nJets]
   Float_t         IP2d3[40];   //[nJets]
   Float_t         IP2dError3[40];   //[nJets]
   Float_t         IP2dProbability3[40];   //[nJets]
   Float_t         IP2dTrackPtRel3[40];   //[nJets]
   Int_t           IP3dTrackQuality4[40];   //[nJets]
   Int_t           IP3dHasSharedPix14[40];   //[nJets]
   Int_t           IP3dHasSharedPix24[40];   //[nJets]
   Int_t           IP3dHasSharedPix34[40];   //[nJets]
   Int_t           IP3dHasSharedPixAll4[40];   //[nJets]
   Float_t         IP3d4[40];   //[nJets]
   Float_t         IP3dError4[40];   //[nJets]
   Float_t         IP3dProbability4[40];   //[nJets]
   Float_t         IP3dTrackPtRel4[40];   //[nJets]
   Float_t         IP3dDistJetAxis4[40];   //[nJets]
   Float_t         IP3dDecayLength4[40];   //[nJets]
   Float_t         IP3dDeltaR4[40];   //[nJets]
   Float_t         IP3dMomentum4[40];   //[nJets]
   Float_t         IP3dTransverseMomentum4[40];   //[nJets]
   Float_t         IP3dEta4[40];   //[nJets]
   Float_t         IP3dPhi4[40];   //[nJets]
   Int_t           IP3dNHits4[40];   //[nJets]
   Int_t           IP3dNPixelHits4[40];   //[nJets]
   Float_t         IP3dNormChi24[40];   //[nJets]
   Int_t           IP2dTrackQuality4[40];   //[nJets]
   Float_t         IP2d4[40];   //[nJets]
   Float_t         IP2dError4[40];   //[nJets]
   Float_t         IP2dProbability4[40];   //[nJets]
   Float_t         IP2dTrackPtRel4[40];   //[nJets]
   Int_t           nElectrons[40];   //[nJets]
   Float_t         electronPt[40];   //[nJets]
   Float_t         electronEta[40];   //[nJets]
   Float_t         electronPhi[40];   //[nJets]
   Int_t           electronNHits[40];   //[nJets]
   Int_t           electronNExpectedOuterHits[40];   //[nJets]
   Int_t           electronNPixelHits[40];   //[nJets]
   Float_t         electronNChi2[40];   //[nJets]
   Float_t         electronPtRel[40];   //[nJets]
   Float_t         electronSip2d[40];   //[nJets]
   Float_t         electronIp2d[40];   //[nJets]
   Float_t         electronIpe2d[40];   //[nJets]
   Float_t         electronSip3d[40];   //[nJets]
   Float_t         electronIp3d[40];   //[nJets]
   Float_t         electronIpe3d[40];   //[nJets]
   Float_t         electronP0Par[40];   //[nJets]
   Float_t         electronDeltaR[40];   //[nJets]
   Float_t         electronEtaRel[40];   //[nJets]
   Float_t         electronRatio[40];   //[nJets]
   Int_t           electronTrackQuality[40];   //[nJets]
   Float_t         electronRatioRel[40];   //[nJets]
   Int_t           nMuons[40];   //[nJets]
   Bool_t          muon1IsGlobal[40];   //[nJets]
   Bool_t          muon1IsTracker[40];   //[nJets]
   Bool_t          muon1IsStandalone[40];   //[nJets]
   Float_t         muon1Pt[40];   //[nJets]
   Float_t         muon1Eta[40];   //[nJets]
   Float_t         muon1Phi[40];   //[nJets]
   Int_t           muon1NumberOfMatches[40];   //[nJets]
   Int_t           muon1GlobalMuonHits[40];   //[nJets]
   Int_t           muon1InnerValidHits[40];   //[nJets]
   Int_t           muon1NExpectedOuterHits[40];   //[nJets]
   Int_t           muon1NPixelHits[40];   //[nJets]
   Float_t         muon1InnerNChi2[40];   //[nJets]
   Float_t         muon1GlobalNChi2[40];   //[nJets]
   Float_t         muon1VzPVDist[40];   //[nJets]
   Float_t         muon1PtRel[40];   //[nJets]
   Float_t         muon1Sip2d[40];   //[nJets]
   Float_t         muon1Ip2d[40];   //[nJets]
   Float_t         muon1Ipe2d[40];   //[nJets]
   Float_t         muon1Sip3d[40];   //[nJets]
   Float_t         muon1Ip3d[40];   //[nJets]
   Float_t         muon1Ipe3d[40];   //[nJets]
   Float_t         muon1P0Par[40];   //[nJets]
   Float_t         muon1DeltaR[40];   //[nJets]
   Float_t         muon1EtaRel[40];   //[nJets]
   Float_t         muon1Ratio[40];   //[nJets]
   Int_t           muon1TrackQuality[40];   //[nJets]
   Float_t         muon1RatioRel[40];   //[nJets]
   Bool_t          muon2IsGlobal[40];   //[nJets]
   Bool_t          muon2IsTracker[40];   //[nJets]
   Bool_t          muon2IsStandalone[40];   //[nJets]
   Float_t         muon2Pt[40];   //[nJets]
   Float_t         muon2Eta[40];   //[nJets]
   Float_t         muon2Phi[40];   //[nJets]
   Int_t           muon2NumberOfMatches[40];   //[nJets]
   Int_t           muon2GlobalMuonHits[40];   //[nJets]
   Int_t           muon2InnerValidHits[40];   //[nJets]
   Int_t           muon2NExpectedOuterHits[40];   //[nJets]
   Int_t           muon2NPixelHits[40];   //[nJets]
   Float_t         muon2InnerNChi2[40];   //[nJets]
   Float_t         muon2GlobalNChi2[40];   //[nJets]
   Float_t         muon2VzPVDist[40];   //[nJets]
   Float_t         muon2PtRel[40];   //[nJets]
   Float_t         muon2Sip2d[40];   //[nJets]
   Float_t         muon2Ip2d[40];   //[nJets]
   Float_t         muon2Ipe2d[40];   //[nJets]
   Float_t         muon2Sip3d[40];   //[nJets]
   Float_t         muon2Ip3d[40];   //[nJets]
   Float_t         muon2Ipe3d[40];   //[nJets]
   Float_t         muon2P0Par[40];   //[nJets]
   Float_t         muon2DeltaR[40];   //[nJets]
   Float_t         muon2EtaRel[40];   //[nJets]
   Float_t         muon2Ratio[40];   //[nJets]
   Int_t           muon2TrackQuality[40];   //[nJets]
   Float_t         muon2RatioRel[40];   //[nJets]
   Bool_t          muon3IsGlobal[40];   //[nJets]
   Bool_t          muon3IsTracker[40];   //[nJets]
   Bool_t          muon3IsStandalone[40];   //[nJets]
   Float_t         muon3Pt[40];   //[nJets]
   Float_t         muon3Eta[40];   //[nJets]
   Float_t         muon3Phi[40];   //[nJets]
   Int_t           muon3NumberOfMatches[40];   //[nJets]
   Int_t           muon3GlobalMuonHits[40];   //[nJets]
   Int_t           muon3InnerValidHits[40];   //[nJets]
   Int_t           muon3NExpectedOuterHits[40];   //[nJets]
   Int_t           muon3NPixelHits[40];   //[nJets]
   Float_t         muon3InnerNChi2[40];   //[nJets]
   Float_t         muon3GlobalNChi2[40];   //[nJets]
   Float_t         muon3VzPVDist[40];   //[nJets]
   Float_t         muon3PtRel[40];   //[nJets]
   Float_t         muon3Sip2d[40];   //[nJets]
   Float_t         muon3Ip2d[40];   //[nJets]
   Float_t         muon3Ipe2d[40];   //[nJets]
   Float_t         muon3Sip3d[40];   //[nJets]
   Float_t         muon3Ip3d[40];   //[nJets]
   Float_t         muon3Ipe3d[40];   //[nJets]
   Float_t         muon3P0Par[40];   //[nJets]
   Float_t         muon3DeltaR[40];   //[nJets]
   Float_t         muon3EtaRel[40];   //[nJets]
   Float_t         muon3Ratio[40];   //[nJets]
   Int_t           muon3TrackQuality[40];   //[nJets]
   Float_t         muon3RatioRel[40];   //[nJets]
   Bool_t          muon4IsGlobal[40];   //[nJets]
   Bool_t          muon4IsTracker[40];   //[nJets]
   Bool_t          muon4IsStandalone[40];   //[nJets]
   Float_t         muon4Pt[40];   //[nJets]
   Float_t         muon4Eta[40];   //[nJets]
   Float_t         muon4Phi[40];   //[nJets]
   Int_t           muon4NumberOfMatches[40];   //[nJets]
   Int_t           muon4GlobalMuonHits[40];   //[nJets]
   Int_t           muon4InnerValidHits[40];   //[nJets]
   Int_t           muon4NExpectedOuterHits[40];   //[nJets]
   Int_t           muon4NPixelHits[40];   //[nJets]
   Float_t         muon4InnerNChi2[40];   //[nJets]
   Float_t         muon4GlobalNChi2[40];   //[nJets]
   Float_t         muon4VzPVDist[40];   //[nJets]
   Float_t         muon4PtRel[40];   //[nJets]
   Float_t         muon4Sip2d[40];   //[nJets]
   Float_t         muon4Ip2d[40];   //[nJets]
   Float_t         muon4Ipe2d[40];   //[nJets]
   Float_t         muon4Sip3d[40];   //[nJets]
   Float_t         muon4Ip3d[40];   //[nJets]
   Float_t         muon4Ipe3d[40];   //[nJets]
   Float_t         muon4P0Par[40];   //[nJets]
   Float_t         muon4DeltaR[40];   //[nJets]
   Float_t         muon4EtaRel[40];   //[nJets]
   Float_t         muon4Ratio[40];   //[nJets]
   Int_t           muon4TrackQuality[40];   //[nJets]
   Float_t         muon4RatioRel[40];   //[nJets]
   Float_t         standardCombinedSecondaryVertexMVAPFBJetTags[40];   //[nJets]
   Float_t         standardCombinedSecondaryVertexPFBJetTags[40];   //[nJets]
   Float_t         standardGhostTrackPFBJetTags[40];   //[nJets]
   Float_t         standardJetBProbabilityPFBJetTags[40];   //[nJets]
   Float_t         standardJetProbabilityPFBJetTags[40];   //[nJets]
   Float_t         standardSimpleSecondaryVertexHighEffPFBJetTags[40];   //[nJets]
   Float_t         standardSimpleSecondaryVertexHighPurPFBJetTags[40];   //[nJets]
   Float_t         standardSoftElectronByIP3dPFBJetTags[40];   //[nJets]
   Float_t         standardSoftElectronByPtPFBJetTags[40];   //[nJets]
   Float_t         standardSoftMuonByIP3dPFBJetTags[40];   //[nJets]
   Float_t         standardSoftMuonByPtPFBJetTags[40];   //[nJets]
   Float_t         standardSoftMuonPFBJetTags[40];   //[nJets]
   Float_t         standardTrackCountingHighEffPFBJetTags[40];   //[nJets]
   Float_t         standardTrackCountingHighPurPFBJetTags[40];   //[nJets]

   // List of branches
   TBranch        *b_triggerHLTL1Jet6U;   //!
   TBranch        *b_triggerHLTL1Jet10U;   //!
   TBranch        *b_triggerHLTJet15U;   //!
   TBranch        *b_triggerHLTJet30U;   //!
   TBranch        *b_triggerHLTJet50U;   //!
   TBranch        *b_triggerHLTJet70U;   //!
   TBranch        *b_triggerHLTJet100U;   //!
   TBranch        *b_isGluonSplitting;   //!
   TBranch        *b_eventNumber;   //!
   TBranch        *b_runNumber;   //!
   TBranch        *b_lumiBlockNumber;   //!
   TBranch        *b_numberOfPrimaryVertices;   //!
   TBranch        *b_pthat;   //!
   TBranch        *b_nJets;   //!
   TBranch        *b_jetPt;   //!
   TBranch        *b_jetEta;   //!
   TBranch        *b_jetPhi;   //!
   TBranch        *b_jetEMFraction;   //!
   TBranch        *b_jetChargedEmEnergyFraction;   //!
   TBranch        *b_jetNeutralEmEnergyFraction;   //!
   TBranch        *b_jetChargedHadronEnergyFraction;   //!
   TBranch        *b_jetNeutralHadronEnergyFraction;   //!
   TBranch        *b_jetChargedMultiplicity;   //!
   TBranch        *b_jetMass;   //!
   TBranch        *b_jetnConstituents;   //!
   TBranch        *b_jetnTracks;   //!
   TBranch        *b_jetVertexChi2;   //!
   TBranch        *b_jetVertexChi2Ndof;   //!
   TBranch        *b_jetVertexNormalizedChi2;   //!
   TBranch        *b_nTracks;   //!
   TBranch        *b_trackJetIndex;   //!
   TBranch        *b_trackSelected;   //!
   TBranch        *b_trackTransverseMomentum;   //!
   TBranch        *b_trackEta;   //!
   TBranch        *b_trackPhi;   //!
   TBranch        *b_trackMomentum;   //!
   TBranch        *b_trackNHits;   //!
   TBranch        *b_trackNPixelHits;   //!
   TBranch        *b_trackChi2;   //!
   TBranch        *b_trackNormChi2;   //!
   TBranch        *b_trackQuality;   //!
   TBranch        *b_trackLongitudinalImpactParameter;   //!
   TBranch        *b_trackIP;   //!
   TBranch        *b_trackDecayLength;   //!
   TBranch        *b_trackDistJetAxis;   //!
   TBranch        *b_trackDeltaR;   //!
   TBranch        *b_trackIP3d;   //!
   TBranch        *b_trackIP2d;   //!
   TBranch        *b_trackIP3dError;   //!
   TBranch        *b_trackIP2dError;   //!
   TBranch        *b_trackHasSharedPix1;   //!
   TBranch        *b_trackHasSharedPix2;   //!
   TBranch        *b_trackHasSharedPix3;   //!
   TBranch        *b_trackHasSharedPixAll;   //!
   TBranch        *b_MCTrueFlavor;   //!
   TBranch        *b_SV3dDistance;   //!
   TBranch        *b_SV3dDistanceError;   //!
   TBranch        *b_SV2dDistance;   //!
   TBranch        *b_SV2dDistanceError;   //!
   TBranch        *b_SVChi2;   //!
   TBranch        *b_SVIPFirstAboveCharm;   //!
   TBranch        *b_SVDegreesOfFreedom;   //!
   TBranch        *b_SVNormChi2;   //!
   TBranch        *b_SVnSelectedTracks;   //!
   TBranch        *b_SVMass;   //!
   TBranch        *b_SVEnergyRatio;   //!
   TBranch        *b_SVnVertices;   //!
   TBranch        *b_SVnVertexTracks;   //!
   TBranch        *b_SVnVertexTracksAll;   //!
   TBranch        *b_SVnFirstVertexTracks;   //!
   TBranch        *b_SVnFirstVertexTracksAll;   //!
   TBranch        *b_SVjetDeltaR;   //!
   TBranch        *b_SVvtxSumVtxDirDeltaR;   //!
   TBranch        *b_SVvtxSumJetDeltaR;   //!
   TBranch        *b_IPnSelectedTracks;   //!
   TBranch        *b_IPghostTrackPt;   //!
   TBranch        *b_IPghostTrackPtRel;   //!
   TBranch        *b_IPghostTrackEta;   //!
   TBranch        *b_IPghostTrackPhi;   //!
   TBranch        *b_IPghostTrackDeltaR;   //!
   TBranch        *b_IPPix1SharedHits;   //!
   TBranch        *b_IPPix1TotalHits;   //!
   TBranch        *b_IPPix2SharedHits;   //!
   TBranch        *b_IPPix2TotalHits;   //!
   TBranch        *b_IPPix3SharedHits;   //!
   TBranch        *b_IPPix3TotalHits;   //!
   TBranch        *b_IPPixAllSharedHits;   //!
   TBranch        *b_IPPixAllTotalHits;   //!
   TBranch        *b_IP3dTrackQuality1;   //!
   TBranch        *b_IP3dHasSharedPix11;   //!
   TBranch        *b_IP3dHasSharedPix21;   //!
   TBranch        *b_IP3dHasSharedPix31;   //!
   TBranch        *b_IP3dHasSharedPixAll1;   //!
   TBranch        *b_IP3d1;   //!
   TBranch        *b_IP3dError1;   //!
   TBranch        *b_IP3dProbability1;   //!
   TBranch        *b_IP3dTrackPtRel1;   //!
   TBranch        *b_IP3dDistJetAxis1;   //!
   TBranch        *b_IP3dDecayLength1;   //!
   TBranch        *b_IP3dDeltaR1;   //!
   TBranch        *b_IP3dMomentum1;   //!
   TBranch        *b_IP3dTransverseMomentum1;   //!
   TBranch        *b_IP3dEta1;   //!
   TBranch        *b_IP3dPhi1;   //!
   TBranch        *b_IP3dNHits1;   //!
   TBranch        *b_IP3dNPixelHits1;   //!
   TBranch        *b_IP3dNormChi21;   //!
   TBranch        *b_IP2dTrackQuality1;   //!
   TBranch        *b_IP2d1;   //!
   TBranch        *b_IP2dError1;   //!
   TBranch        *b_IP2dProbability1;   //!
   TBranch        *b_IP2dTrackPtRel1;   //!
   TBranch        *b_IP3dTrackQuality2;   //!
   TBranch        *b_IP3dHasSharedPix12;   //!
   TBranch        *b_IP3dHasSharedPix22;   //!
   TBranch        *b_IP3dHasSharedPix32;   //!
   TBranch        *b_IP3dHasSharedPixAll2;   //!
   TBranch        *b_IP3d2;   //!
   TBranch        *b_IP3dError2;   //!
   TBranch        *b_IP3dProbability2;   //!
   TBranch        *b_IP3dTrackPtRel2;   //!
   TBranch        *b_IP3dDistJetAxis2;   //!
   TBranch        *b_IP3dDecayLength2;   //!
   TBranch        *b_IP3dDeltaR2;   //!
   TBranch        *b_IP3dMomentum2;   //!
   TBranch        *b_IP3dTransverseMomentum2;   //!
   TBranch        *b_IP3dEta2;   //!
   TBranch        *b_IP3dPhi2;   //!
   TBranch        *b_IP3dNHits2;   //!
   TBranch        *b_IP3dNPixelHits2;   //!
   TBranch        *b_IP3dNormChi22;   //!
   TBranch        *b_IP2dTrackQuality2;   //!
   TBranch        *b_IP2d2;   //!
   TBranch        *b_IP2dError2;   //!
   TBranch        *b_IP2dProbability2;   //!
   TBranch        *b_IP2dTrackPtRel2;   //!
   TBranch        *b_IP3dTrackQuality3;   //!
   TBranch        *b_IP3dHasSharedPix13;   //!
   TBranch        *b_IP3dHasSharedPix23;   //!
   TBranch        *b_IP3dHasSharedPix33;   //!
   TBranch        *b_IP3dHasSharedPixAll3;   //!
   TBranch        *b_IP3d3;   //!
   TBranch        *b_IP3dError3;   //!
   TBranch        *b_IP3dProbability3;   //!
   TBranch        *b_IP3dTrackPtRel3;   //!
   TBranch        *b_IP3dDistJetAxis3;   //!
   TBranch        *b_IP3dDecayLength3;   //!
   TBranch        *b_IP3dDeltaR3;   //!
   TBranch        *b_IP3dMomentum3;   //!
   TBranch        *b_IP3dTransverseMomentum3;   //!
   TBranch        *b_IP3dEta3;   //!
   TBranch        *b_IP3dPhi3;   //!
   TBranch        *b_IP3dNHits3;   //!
   TBranch        *b_IP3dNPixelHits3;   //!
   TBranch        *b_IP3dNormChi23;   //!
   TBranch        *b_IP2dTrackQuality3;   //!
   TBranch        *b_IP2d3;   //!
   TBranch        *b_IP2dError3;   //!
   TBranch        *b_IP2dProbability3;   //!
   TBranch        *b_IP2dTrackPtRel3;   //!
   TBranch        *b_IP3dTrackQuality4;   //!
   TBranch        *b_IP3dHasSharedPix14;   //!
   TBranch        *b_IP3dHasSharedPix24;   //!
   TBranch        *b_IP3dHasSharedPix34;   //!
   TBranch        *b_IP3dHasSharedPixAll4;   //!
   TBranch        *b_IP3d4;   //!
   TBranch        *b_IP3dError4;   //!
   TBranch        *b_IP3dProbability4;   //!
   TBranch        *b_IP3dTrackPtRel4;   //!
   TBranch        *b_IP3dDistJetAxis4;   //!
   TBranch        *b_IP3dDecayLength4;   //!
   TBranch        *b_IP3dDeltaR4;   //!
   TBranch        *b_IP3dMomentum4;   //!
   TBranch        *b_IP3dTransverseMomentum4;   //!
   TBranch        *b_IP3dEta4;   //!
   TBranch        *b_IP3dPhi4;   //!
   TBranch        *b_IP3dNHits4;   //!
   TBranch        *b_IP3dNPixelHits4;   //!
   TBranch        *b_IP3dNormChi24;   //!
   TBranch        *b_IP2dTrackQuality4;   //!
   TBranch        *b_IP2d4;   //!
   TBranch        *b_IP2dError4;   //!
   TBranch        *b_IP2dProbability4;   //!
   TBranch        *b_IP2dTrackPtRel4;   //!
   TBranch        *b_nElectrons;   //!
   TBranch        *b_electronPt;   //!
   TBranch        *b_electronEta;   //!
   TBranch        *b_electronPhi;   //!
   TBranch        *b_electronNHits;   //!
   TBranch        *b_electronNExpectedOuterHits;   //!
   TBranch        *b_electronNPixelHits;   //!
   TBranch        *b_electronNChi2;   //!
   TBranch        *b_electronPtRel;   //!
   TBranch        *b_electronSip2d;   //!
   TBranch        *b_electronIp2d;   //!
   TBranch        *b_electronIpe2d;   //!
   TBranch        *b_electronSip3d;   //!
   TBranch        *b_electronIp3d;   //!
   TBranch        *b_electronIpe3d;   //!
   TBranch        *b_electronP0Par;   //!
   TBranch        *b_electronDeltaR;   //!
   TBranch        *b_electronEtaRel;   //!
   TBranch        *b_electronRatio;   //!
   TBranch        *b_electronTrackQuality;   //!
   TBranch        *b_electronRatioRel;   //!
   TBranch        *b_nMuons;   //!
   TBranch        *b_muon1IsGlobal;   //!
   TBranch        *b_muon1IsTracker;   //!
   TBranch        *b_muon1IsStandalone;   //!
   TBranch        *b_muon1Pt;   //!
   TBranch        *b_muon1Eta;   //!
   TBranch        *b_muon1Phi;   //!
   TBranch        *b_muon1NumberOfMatches;   //!
   TBranch        *b_muon1GlobalMuonHits;   //!
   TBranch        *b_muon1InnerValidHits;   //!
   TBranch        *b_muon1NExpectedOuterHits;   //!
   TBranch        *b_muon1NPixelHits;   //!
   TBranch        *b_muon1InnerNChi2;   //!
   TBranch        *b_muon1GlobalNChi2;   //!
   TBranch        *b_muon1VzPVDist;   //!
   TBranch        *b_muon1PtRel;   //!
   TBranch        *b_muon1Sip2d;   //!
   TBranch        *b_muon1Ip2d;   //!
   TBranch        *b_muon1Ipe2d;   //!
   TBranch        *b_muon1Sip3d;   //!
   TBranch        *b_muon1Ip3d;   //!
   TBranch        *b_muon1Ipe3d;   //!
   TBranch        *b_muon1P0Par;   //!
   TBranch        *b_muon1DeltaR;   //!
   TBranch        *b_muon1EtaRel;   //!
   TBranch        *b_muon1Ratio;   //!
   TBranch        *b_muon1TrackQuality;   //!
   TBranch        *b_muon1RatioRel;   //!
   TBranch        *b_muon2IsGlobal;   //!
   TBranch        *b_muon2IsTracker;   //!
   TBranch        *b_muon2IsStandalone;   //!
   TBranch        *b_muon2Pt;   //!
   TBranch        *b_muon2Eta;   //!
   TBranch        *b_muon2Phi;   //!
   TBranch        *b_muon2NumberOfMatches;   //!
   TBranch        *b_muon2GlobalMuonHits;   //!
   TBranch        *b_muon2InnerValidHits;   //!
   TBranch        *b_muon2NExpectedOuterHits;   //!
   TBranch        *b_muon2NPixelHits;   //!
   TBranch        *b_muon2InnerNChi2;   //!
   TBranch        *b_muon2GlobalNChi2;   //!
   TBranch        *b_muon2VzPVDist;   //!
   TBranch        *b_muon2PtRel;   //!
   TBranch        *b_muon2Sip2d;   //!
   TBranch        *b_muon2Ip2d;   //!
   TBranch        *b_muon2Ipe2d;   //!
   TBranch        *b_muon2Sip3d;   //!
   TBranch        *b_muon2Ip3d;   //!
   TBranch        *b_muon2Ipe3d;   //!
   TBranch        *b_muon2P0Par;   //!
   TBranch        *b_muon2DeltaR;   //!
   TBranch        *b_muon2EtaRel;   //!
   TBranch        *b_muon2Ratio;   //!
   TBranch        *b_muon2TrackQuality;   //!
   TBranch        *b_muon2RatioRel;   //!
   TBranch        *b_muon3IsGlobal;   //!
   TBranch        *b_muon3IsTracker;   //!
   TBranch        *b_muon3IsStandalone;   //!
   TBranch        *b_muon3Pt;   //!
   TBranch        *b_muon3Eta;   //!
   TBranch        *b_muon3Phi;   //!
   TBranch        *b_muon3NumberOfMatches;   //!
   TBranch        *b_muon3GlobalMuonHits;   //!
   TBranch        *b_muon3InnerValidHits;   //!
   TBranch        *b_muon3NExpectedOuterHits;   //!
   TBranch        *b_muon3NPixelHits;   //!
   TBranch        *b_muon3InnerNChi2;   //!
   TBranch        *b_muon3GlobalNChi2;   //!
   TBranch        *b_muon3VzPVDist;   //!
   TBranch        *b_muon3PtRel;   //!
   TBranch        *b_muon3Sip2d;   //!
   TBranch        *b_muon3Ip2d;   //!
   TBranch        *b_muon3Ipe2d;   //!
   TBranch        *b_muon3Sip3d;   //!
   TBranch        *b_muon3Ip3d;   //!
   TBranch        *b_muon3Ipe3d;   //!
   TBranch        *b_muon3P0Par;   //!
   TBranch        *b_muon3DeltaR;   //!
   TBranch        *b_muon3EtaRel;   //!
   TBranch        *b_muon3Ratio;   //!
   TBranch        *b_muon3TrackQuality;   //!
   TBranch        *b_muon3RatioRel;   //!
   TBranch        *b_muon4IsGlobal;   //!
   TBranch        *b_muon4IsTracker;   //!
   TBranch        *b_muon4IsStandalone;   //!
   TBranch        *b_muon4Pt;   //!
   TBranch        *b_muon4Eta;   //!
   TBranch        *b_muon4Phi;   //!
   TBranch        *b_muon4NumberOfMatches;   //!
   TBranch        *b_muon4GlobalMuonHits;   //!
   TBranch        *b_muon4InnerValidHits;   //!
   TBranch        *b_muon4NExpectedOuterHits;   //!
   TBranch        *b_muon4NPixelHits;   //!
   TBranch        *b_muon4InnerNChi2;   //!
   TBranch        *b_muon4GlobalNChi2;   //!
   TBranch        *b_muon4VzPVDist;   //!
   TBranch        *b_muon4PtRel;   //!
   TBranch        *b_muon4Sip2d;   //!
   TBranch        *b_muon4Ip2d;   //!
   TBranch        *b_muon4Ipe2d;   //!
   TBranch        *b_muon4Sip3d;   //!
   TBranch        *b_muon4Ip3d;   //!
   TBranch        *b_muon4Ipe3d;   //!
   TBranch        *b_muon4P0Par;   //!
   TBranch        *b_muon4DeltaR;   //!
   TBranch        *b_muon4EtaRel;   //!
   TBranch        *b_muon4Ratio;   //!
   TBranch        *b_muon4TrackQuality;   //!
   TBranch        *b_muon4RatioRel;   //!
   TBranch        *b_standardCombinedSecondaryVertexMVAPFBJetTags;   //!
   TBranch        *b_standardCombinedSecondaryVertexPFBJetTags;   //!
   TBranch        *b_standardGhostTrackPFBJetTags;   //!
   TBranch        *b_standardJetBProbabilityPFBJetTags;   //!
   TBranch        *b_standardJetProbabilityPFBJetTags;   //!
   TBranch        *b_standardSimpleSecondaryVertexHighEffPFBJetTags;   //!
   TBranch        *b_standardSimpleSecondaryVertexHighPurPFBJetTags;   //!
   TBranch        *b_standardSoftElectronByIP3dPFBJetTags;   //!
   TBranch        *b_standardSoftElectronByPtPFBJetTags;   //!
   TBranch        *b_standardSoftMuonByIP3dPFBJetTags;   //!
   TBranch        *b_standardSoftMuonByPtPFBJetTags;   //!
   TBranch        *b_standardSoftMuonPFBJetTags;   //!
   TBranch        *b_standardTrackCountingHighEffPFBJetTags;   //!
   TBranch        *b_standardTrackCountingHighPurPFBJetTags;   //!

   MuonSelector(TTree * /*tree*/ =0) { }
   virtual ~MuonSelector() { }
   virtual Int_t   Version() const { return 2; }
   virtual void    Begin(TTree *tree);
   virtual void    SlaveBegin(TTree *tree);
   virtual void    Init(TTree *tree);
   virtual Bool_t  Notify();
   virtual Bool_t  Process(Long64_t entry);
   virtual Int_t   GetEntry(Long64_t entry, Int_t getall = 0) { return fChain ? fChain->GetTree()->GetEntry(entry, getall) : 0; }
   virtual void    SetOption(const char *option) { fOption = option; }
   virtual void    SetObject(TObject *obj) { fObject = obj; }
   virtual void    SetInputList(TList *input) { fInput = input; }
   virtual TList  *GetOutputList() const { return fOutput; }
   virtual void    SlaveTerminate();
   virtual void    Terminate();

   virtual void    MuSetUp(bool isData_, TH1D*dataHist_, TH1D* mcHistb_, TH1D* mcHistbglusplit_, TH1D* mcHistc_, TH1D* mcHistl_, TH1D* mcHistn_, informationMuonCuts info_){
     isData = isData_;
     dataHist = dataHist_;
     mcHistb = mcHistb_;
     mcHistbglusplit = mcHistbglusplit_;
     mcHistc = mcHistc_;
     mcHistl = mcHistl_;
     mcHistn = mcHistn_;
     info = info_;
   }

   ClassDef(MuonSelector,0);
};

#endif

#ifdef MuonSelector_cxx
void MuonSelector::Init(TTree *tree)
{
   // The Init() function is called when the selector needs to initialize
   // a new tree or chain. Typically here the branch addresses and branch
   // pointers of the tree will be set.
   // It is normally not necessary to make changes to the generated
   // code, but the routine can be extended by the user if needed.
   // Init() will be called many times when running on PROOF
   // (once per file to be processed).

   // Set branch addresses and branch pointers
   if (!tree) return;
   fChain = tree;
   fChain->SetMakeClass(1);

   fChain->SetBranchAddress("triggerHLTL1Jet6U", &triggerHLTL1Jet6U, &b_triggerHLTL1Jet6U);
   fChain->SetBranchAddress("triggerHLTL1Jet10U", &triggerHLTL1Jet10U, &b_triggerHLTL1Jet10U);
   fChain->SetBranchAddress("triggerHLTJet15U", &triggerHLTJet15U, &b_triggerHLTJet15U);
   fChain->SetBranchAddress("triggerHLTJet30U", &triggerHLTJet30U, &b_triggerHLTJet30U);
   fChain->SetBranchAddress("triggerHLTJet50U", &triggerHLTJet50U, &b_triggerHLTJet50U);
   fChain->SetBranchAddress("triggerHLTJet70U", &triggerHLTJet70U, &b_triggerHLTJet70U);
   fChain->SetBranchAddress("triggerHLTJet100U", &triggerHLTJet100U, &b_triggerHLTJet100U);
   fChain->SetBranchAddress("isGluonSplitting", &isGluonSplitting, &b_isGluonSplitting);
   fChain->SetBranchAddress("eventNumber", &eventNumber, &b_eventNumber);
   fChain->SetBranchAddress("runNumber", &runNumber, &b_runNumber);
   fChain->SetBranchAddress("lumiBlockNumber", &lumiBlockNumber, &b_lumiBlockNumber);
   fChain->SetBranchAddress("numberOfPrimaryVertices", &numberOfPrimaryVertices, &b_numberOfPrimaryVertices);
   fChain->SetBranchAddress("pthat", &pthat, &b_pthat);
   fChain->SetBranchAddress("nJets", &nJets, &b_nJets);
   fChain->SetBranchAddress("jetPt", jetPt, &b_jetPt);
   fChain->SetBranchAddress("jetEta", jetEta, &b_jetEta);
   fChain->SetBranchAddress("jetPhi", jetPhi, &b_jetPhi);
   fChain->SetBranchAddress("jetEMFraction", jetEMFraction, &b_jetEMFraction);
   fChain->SetBranchAddress("jetChargedEmEnergyFraction", jetChargedEmEnergyFraction, &b_jetChargedEmEnergyFraction);
   fChain->SetBranchAddress("jetNeutralEmEnergyFraction", jetNeutralEmEnergyFraction, &b_jetNeutralEmEnergyFraction);
   fChain->SetBranchAddress("jetChargedHadronEnergyFraction", jetChargedHadronEnergyFraction, &b_jetChargedHadronEnergyFraction);
   fChain->SetBranchAddress("jetNeutralHadronEnergyFraction", jetNeutralHadronEnergyFraction, &b_jetNeutralHadronEnergyFraction);
   fChain->SetBranchAddress("jetChargedMultiplicity", jetChargedMultiplicity, &b_jetChargedMultiplicity);
   fChain->SetBranchAddress("jetMass", jetMass, &b_jetMass);
   fChain->SetBranchAddress("jetnConstituents", jetnConstituents, &b_jetnConstituents);
   fChain->SetBranchAddress("jetnTracks", jetnTracks, &b_jetnTracks);
   fChain->SetBranchAddress("jetVertexChi2", jetVertexChi2, &b_jetVertexChi2);
   fChain->SetBranchAddress("jetVertexChi2Ndof", jetVertexChi2Ndof, &b_jetVertexChi2Ndof);
   fChain->SetBranchAddress("jetVertexNormalizedChi2", jetVertexNormalizedChi2, &b_jetVertexNormalizedChi2);
   fChain->SetBranchAddress("nTracks", &nTracks, &b_nTracks);
   fChain->SetBranchAddress("trackJetIndex", trackJetIndex, &b_trackJetIndex);
   fChain->SetBranchAddress("trackSelected", trackSelected, &b_trackSelected);
   fChain->SetBranchAddress("trackTransverseMomentum", trackTransverseMomentum, &b_trackTransverseMomentum);
   fChain->SetBranchAddress("trackEta", trackEta, &b_trackEta);
   fChain->SetBranchAddress("trackPhi", trackPhi, &b_trackPhi);
   fChain->SetBranchAddress("trackMomentum", trackMomentum, &b_trackMomentum);
   fChain->SetBranchAddress("trackNHits", trackNHits, &b_trackNHits);
   fChain->SetBranchAddress("trackNPixelHits", trackNPixelHits, &b_trackNPixelHits);
   fChain->SetBranchAddress("trackChi2", trackChi2, &b_trackChi2);
   fChain->SetBranchAddress("trackNormChi2", trackNormChi2, &b_trackNormChi2);
   fChain->SetBranchAddress("trackQuality", trackQuality, &b_trackQuality);
   fChain->SetBranchAddress("trackLongitudinalImpactParameter", trackLongitudinalImpactParameter, &b_trackLongitudinalImpactParameter);
   fChain->SetBranchAddress("trackIP", trackIP, &b_trackIP);
   fChain->SetBranchAddress("trackDecayLength", trackDecayLength, &b_trackDecayLength);
   fChain->SetBranchAddress("trackDistJetAxis", trackDistJetAxis, &b_trackDistJetAxis);
   fChain->SetBranchAddress("trackDeltaR", trackDeltaR, &b_trackDeltaR);
   fChain->SetBranchAddress("trackIP3d", trackIP3d, &b_trackIP3d);
   fChain->SetBranchAddress("trackIP2d", trackIP2d, &b_trackIP2d);
   fChain->SetBranchAddress("trackIP3dError", trackIP3dError, &b_trackIP3dError);
   fChain->SetBranchAddress("trackIP2dError", trackIP2dError, &b_trackIP2dError);
   fChain->SetBranchAddress("trackHasSharedPix1", trackHasSharedPix1, &b_trackHasSharedPix1);
   fChain->SetBranchAddress("trackHasSharedPix2", trackHasSharedPix2, &b_trackHasSharedPix2);
   fChain->SetBranchAddress("trackHasSharedPix3", trackHasSharedPix3, &b_trackHasSharedPix3);
   fChain->SetBranchAddress("trackHasSharedPixAll", trackHasSharedPixAll, &b_trackHasSharedPixAll);
   fChain->SetBranchAddress("MCTrueFlavor", MCTrueFlavor, &b_MCTrueFlavor);
   fChain->SetBranchAddress("SV3dDistance", SV3dDistance, &b_SV3dDistance);
   fChain->SetBranchAddress("SV3dDistanceError", SV3dDistanceError, &b_SV3dDistanceError);
   fChain->SetBranchAddress("SV2dDistance", SV2dDistance, &b_SV2dDistance);
   fChain->SetBranchAddress("SV2dDistanceError", SV2dDistanceError, &b_SV2dDistanceError);
   fChain->SetBranchAddress("SVChi2", SVChi2, &b_SVChi2);
   fChain->SetBranchAddress("SVIPFirstAboveCharm", SVIPFirstAboveCharm, &b_SVIPFirstAboveCharm);
   fChain->SetBranchAddress("SVDegreesOfFreedom", SVDegreesOfFreedom, &b_SVDegreesOfFreedom);
   fChain->SetBranchAddress("SVNormChi2", SVNormChi2, &b_SVNormChi2);
   fChain->SetBranchAddress("SVnSelectedTracks", SVnSelectedTracks, &b_SVnSelectedTracks);
   fChain->SetBranchAddress("SVMass", SVMass, &b_SVMass);
   fChain->SetBranchAddress("SVEnergyRatio", SVEnergyRatio, &b_SVEnergyRatio);
   fChain->SetBranchAddress("SVnVertices", SVnVertices, &b_SVnVertices);
   fChain->SetBranchAddress("SVnVertexTracks", SVnVertexTracks, &b_SVnVertexTracks);
   fChain->SetBranchAddress("SVnVertexTracksAll", SVnVertexTracksAll, &b_SVnVertexTracksAll);
   fChain->SetBranchAddress("SVnFirstVertexTracks", SVnFirstVertexTracks, &b_SVnFirstVertexTracks);
   fChain->SetBranchAddress("SVnFirstVertexTracksAll", SVnFirstVertexTracksAll, &b_SVnFirstVertexTracksAll);
   fChain->SetBranchAddress("SVjetDeltaR", SVjetDeltaR, &b_SVjetDeltaR);
   fChain->SetBranchAddress("SVvtxSumVtxDirDeltaR", SVvtxSumVtxDirDeltaR, &b_SVvtxSumVtxDirDeltaR);
   fChain->SetBranchAddress("SVvtxSumJetDeltaR", SVvtxSumJetDeltaR, &b_SVvtxSumJetDeltaR);
   fChain->SetBranchAddress("IPnSelectedTracks", IPnSelectedTracks, &b_IPnSelectedTracks);
   fChain->SetBranchAddress("IPghostTrackPt", IPghostTrackPt, &b_IPghostTrackPt);
   fChain->SetBranchAddress("IPghostTrackPtRel", IPghostTrackPtRel, &b_IPghostTrackPtRel);
   fChain->SetBranchAddress("IPghostTrackEta", IPghostTrackEta, &b_IPghostTrackEta);
   fChain->SetBranchAddress("IPghostTrackPhi", IPghostTrackPhi, &b_IPghostTrackPhi);
   fChain->SetBranchAddress("IPghostTrackDeltaR", IPghostTrackDeltaR, &b_IPghostTrackDeltaR);
   fChain->SetBranchAddress("IPPix1SharedHits", IPPix1SharedHits, &b_IPPix1SharedHits);
   fChain->SetBranchAddress("IPPix1TotalHits", IPPix1TotalHits, &b_IPPix1TotalHits);
   fChain->SetBranchAddress("IPPix2SharedHits", IPPix2SharedHits, &b_IPPix2SharedHits);
   fChain->SetBranchAddress("IPPix2TotalHits", IPPix2TotalHits, &b_IPPix2TotalHits);
   fChain->SetBranchAddress("IPPix3SharedHits", IPPix3SharedHits, &b_IPPix3SharedHits);
   fChain->SetBranchAddress("IPPix3TotalHits", IPPix3TotalHits, &b_IPPix3TotalHits);
   fChain->SetBranchAddress("IPPixAllSharedHits", IPPixAllSharedHits, &b_IPPixAllSharedHits);
   fChain->SetBranchAddress("IPPixAllTotalHits", IPPixAllTotalHits, &b_IPPixAllTotalHits);
   fChain->SetBranchAddress("IP3dTrackQuality1", IP3dTrackQuality1, &b_IP3dTrackQuality1);
   fChain->SetBranchAddress("IP3dHasSharedPix11", IP3dHasSharedPix11, &b_IP3dHasSharedPix11);
   fChain->SetBranchAddress("IP3dHasSharedPix21", IP3dHasSharedPix21, &b_IP3dHasSharedPix21);
   fChain->SetBranchAddress("IP3dHasSharedPix31", IP3dHasSharedPix31, &b_IP3dHasSharedPix31);
   fChain->SetBranchAddress("IP3dHasSharedPixAll1", IP3dHasSharedPixAll1, &b_IP3dHasSharedPixAll1);
   fChain->SetBranchAddress("IP3d1", IP3d1, &b_IP3d1);
   fChain->SetBranchAddress("IP3dError1", IP3dError1, &b_IP3dError1);
   fChain->SetBranchAddress("IP3dProbability1", IP3dProbability1, &b_IP3dProbability1);
   fChain->SetBranchAddress("IP3dTrackPtRel1", IP3dTrackPtRel1, &b_IP3dTrackPtRel1);
   fChain->SetBranchAddress("IP3dDistJetAxis1", IP3dDistJetAxis1, &b_IP3dDistJetAxis1);
   fChain->SetBranchAddress("IP3dDecayLength1", IP3dDecayLength1, &b_IP3dDecayLength1);
   fChain->SetBranchAddress("IP3dDeltaR1", IP3dDeltaR1, &b_IP3dDeltaR1);
   fChain->SetBranchAddress("IP3dMomentum1", IP3dMomentum1, &b_IP3dMomentum1);
   fChain->SetBranchAddress("IP3dTransverseMomentum1", IP3dTransverseMomentum1, &b_IP3dTransverseMomentum1);
   fChain->SetBranchAddress("IP3dEta1", IP3dEta1, &b_IP3dEta1);
   fChain->SetBranchAddress("IP3dPhi1", IP3dPhi1, &b_IP3dPhi1);
   fChain->SetBranchAddress("IP3dNHits1", IP3dNHits1, &b_IP3dNHits1);
   fChain->SetBranchAddress("IP3dNPixelHits1", IP3dNPixelHits1, &b_IP3dNPixelHits1);
   fChain->SetBranchAddress("IP3dNormChi21", IP3dNormChi21, &b_IP3dNormChi21);
   fChain->SetBranchAddress("IP2dTrackQuality1", IP2dTrackQuality1, &b_IP2dTrackQuality1);
   fChain->SetBranchAddress("IP2d1", IP2d1, &b_IP2d1);
   fChain->SetBranchAddress("IP2dError1", IP2dError1, &b_IP2dError1);
   fChain->SetBranchAddress("IP2dProbability1", IP2dProbability1, &b_IP2dProbability1);
   fChain->SetBranchAddress("IP2dTrackPtRel1", IP2dTrackPtRel1, &b_IP2dTrackPtRel1);
   fChain->SetBranchAddress("IP3dTrackQuality2", IP3dTrackQuality2, &b_IP3dTrackQuality2);
   fChain->SetBranchAddress("IP3dHasSharedPix12", IP3dHasSharedPix12, &b_IP3dHasSharedPix12);
   fChain->SetBranchAddress("IP3dHasSharedPix22", IP3dHasSharedPix22, &b_IP3dHasSharedPix22);
   fChain->SetBranchAddress("IP3dHasSharedPix32", IP3dHasSharedPix32, &b_IP3dHasSharedPix32);
   fChain->SetBranchAddress("IP3dHasSharedPixAll2", IP3dHasSharedPixAll2, &b_IP3dHasSharedPixAll2);
   fChain->SetBranchAddress("IP3d2", IP3d2, &b_IP3d2);
   fChain->SetBranchAddress("IP3dError2", IP3dError2, &b_IP3dError2);
   fChain->SetBranchAddress("IP3dProbability2", IP3dProbability2, &b_IP3dProbability2);
   fChain->SetBranchAddress("IP3dTrackPtRel2", IP3dTrackPtRel2, &b_IP3dTrackPtRel2);
   fChain->SetBranchAddress("IP3dDistJetAxis2", IP3dDistJetAxis2, &b_IP3dDistJetAxis2);
   fChain->SetBranchAddress("IP3dDecayLength2", IP3dDecayLength2, &b_IP3dDecayLength2);
   fChain->SetBranchAddress("IP3dDeltaR2", IP3dDeltaR2, &b_IP3dDeltaR2);
   fChain->SetBranchAddress("IP3dMomentum2", IP3dMomentum2, &b_IP3dMomentum2);
   fChain->SetBranchAddress("IP3dTransverseMomentum2", IP3dTransverseMomentum2, &b_IP3dTransverseMomentum2);
   fChain->SetBranchAddress("IP3dEta2", IP3dEta2, &b_IP3dEta2);
   fChain->SetBranchAddress("IP3dPhi2", IP3dPhi2, &b_IP3dPhi2);
   fChain->SetBranchAddress("IP3dNHits2", IP3dNHits2, &b_IP3dNHits2);
   fChain->SetBranchAddress("IP3dNPixelHits2", IP3dNPixelHits2, &b_IP3dNPixelHits2);
   fChain->SetBranchAddress("IP3dNormChi22", IP3dNormChi22, &b_IP3dNormChi22);
   fChain->SetBranchAddress("IP2dTrackQuality2", IP2dTrackQuality2, &b_IP2dTrackQuality2);
   fChain->SetBranchAddress("IP2d2", IP2d2, &b_IP2d2);
   fChain->SetBranchAddress("IP2dError2", IP2dError2, &b_IP2dError2);
   fChain->SetBranchAddress("IP2dProbability2", IP2dProbability2, &b_IP2dProbability2);
   fChain->SetBranchAddress("IP2dTrackPtRel2", IP2dTrackPtRel2, &b_IP2dTrackPtRel2);
   fChain->SetBranchAddress("IP3dTrackQuality3", IP3dTrackQuality3, &b_IP3dTrackQuality3);
   fChain->SetBranchAddress("IP3dHasSharedPix13", IP3dHasSharedPix13, &b_IP3dHasSharedPix13);
   fChain->SetBranchAddress("IP3dHasSharedPix23", IP3dHasSharedPix23, &b_IP3dHasSharedPix23);
   fChain->SetBranchAddress("IP3dHasSharedPix33", IP3dHasSharedPix33, &b_IP3dHasSharedPix33);
   fChain->SetBranchAddress("IP3dHasSharedPixAll3", IP3dHasSharedPixAll3, &b_IP3dHasSharedPixAll3);
   fChain->SetBranchAddress("IP3d3", IP3d3, &b_IP3d3);
   fChain->SetBranchAddress("IP3dError3", IP3dError3, &b_IP3dError3);
   fChain->SetBranchAddress("IP3dProbability3", IP3dProbability3, &b_IP3dProbability3);
   fChain->SetBranchAddress("IP3dTrackPtRel3", IP3dTrackPtRel3, &b_IP3dTrackPtRel3);
   fChain->SetBranchAddress("IP3dDistJetAxis3", IP3dDistJetAxis3, &b_IP3dDistJetAxis3);
   fChain->SetBranchAddress("IP3dDecayLength3", IP3dDecayLength3, &b_IP3dDecayLength3);
   fChain->SetBranchAddress("IP3dDeltaR3", IP3dDeltaR3, &b_IP3dDeltaR3);
   fChain->SetBranchAddress("IP3dMomentum3", IP3dMomentum3, &b_IP3dMomentum3);
   fChain->SetBranchAddress("IP3dTransverseMomentum3", IP3dTransverseMomentum3, &b_IP3dTransverseMomentum3);
   fChain->SetBranchAddress("IP3dEta3", IP3dEta3, &b_IP3dEta3);
   fChain->SetBranchAddress("IP3dPhi3", IP3dPhi3, &b_IP3dPhi3);
   fChain->SetBranchAddress("IP3dNHits3", IP3dNHits3, &b_IP3dNHits3);
   fChain->SetBranchAddress("IP3dNPixelHits3", IP3dNPixelHits3, &b_IP3dNPixelHits3);
   fChain->SetBranchAddress("IP3dNormChi23", IP3dNormChi23, &b_IP3dNormChi23);
   fChain->SetBranchAddress("IP2dTrackQuality3", IP2dTrackQuality3, &b_IP2dTrackQuality3);
   fChain->SetBranchAddress("IP2d3", IP2d3, &b_IP2d3);
   fChain->SetBranchAddress("IP2dError3", IP2dError3, &b_IP2dError3);
   fChain->SetBranchAddress("IP2dProbability3", IP2dProbability3, &b_IP2dProbability3);
   fChain->SetBranchAddress("IP2dTrackPtRel3", IP2dTrackPtRel3, &b_IP2dTrackPtRel3);
   fChain->SetBranchAddress("IP3dTrackQuality4", IP3dTrackQuality4, &b_IP3dTrackQuality4);
   fChain->SetBranchAddress("IP3dHasSharedPix14", IP3dHasSharedPix14, &b_IP3dHasSharedPix14);
   fChain->SetBranchAddress("IP3dHasSharedPix24", IP3dHasSharedPix24, &b_IP3dHasSharedPix24);
   fChain->SetBranchAddress("IP3dHasSharedPix34", IP3dHasSharedPix34, &b_IP3dHasSharedPix34);
   fChain->SetBranchAddress("IP3dHasSharedPixAll4", IP3dHasSharedPixAll4, &b_IP3dHasSharedPixAll4);
   fChain->SetBranchAddress("IP3d4", IP3d4, &b_IP3d4);
   fChain->SetBranchAddress("IP3dError4", IP3dError4, &b_IP3dError4);
   fChain->SetBranchAddress("IP3dProbability4", IP3dProbability4, &b_IP3dProbability4);
   fChain->SetBranchAddress("IP3dTrackPtRel4", IP3dTrackPtRel4, &b_IP3dTrackPtRel4);
   fChain->SetBranchAddress("IP3dDistJetAxis4", IP3dDistJetAxis4, &b_IP3dDistJetAxis4);
   fChain->SetBranchAddress("IP3dDecayLength4", IP3dDecayLength4, &b_IP3dDecayLength4);
   fChain->SetBranchAddress("IP3dDeltaR4", IP3dDeltaR4, &b_IP3dDeltaR4);
   fChain->SetBranchAddress("IP3dMomentum4", IP3dMomentum4, &b_IP3dMomentum4);
   fChain->SetBranchAddress("IP3dTransverseMomentum4", IP3dTransverseMomentum4, &b_IP3dTransverseMomentum4);
   fChain->SetBranchAddress("IP3dEta4", IP3dEta4, &b_IP3dEta4);
   fChain->SetBranchAddress("IP3dPhi4", IP3dPhi4, &b_IP3dPhi4);
   fChain->SetBranchAddress("IP3dNHits4", IP3dNHits4, &b_IP3dNHits4);
   fChain->SetBranchAddress("IP3dNPixelHits4", IP3dNPixelHits4, &b_IP3dNPixelHits4);
   fChain->SetBranchAddress("IP3dNormChi24", IP3dNormChi24, &b_IP3dNormChi24);
   fChain->SetBranchAddress("IP2dTrackQuality4", IP2dTrackQuality4, &b_IP2dTrackQuality4);
   fChain->SetBranchAddress("IP2d4", IP2d4, &b_IP2d4);
   fChain->SetBranchAddress("IP2dError4", IP2dError4, &b_IP2dError4);
   fChain->SetBranchAddress("IP2dProbability4", IP2dProbability4, &b_IP2dProbability4);
   fChain->SetBranchAddress("IP2dTrackPtRel4", IP2dTrackPtRel4, &b_IP2dTrackPtRel4);
   fChain->SetBranchAddress("nElectrons", nElectrons, &b_nElectrons);
   fChain->SetBranchAddress("electronPt", electronPt, &b_electronPt);
   fChain->SetBranchAddress("electronEta", electronEta, &b_electronEta);
   fChain->SetBranchAddress("electronPhi", electronPhi, &b_electronPhi);
   fChain->SetBranchAddress("electronNHits", electronNHits, &b_electronNHits);
   fChain->SetBranchAddress("electronNExpectedOuterHits", electronNExpectedOuterHits, &b_electronNExpectedOuterHits);
   fChain->SetBranchAddress("electronNPixelHits", electronNPixelHits, &b_electronNPixelHits);
   fChain->SetBranchAddress("electronNChi2", electronNChi2, &b_electronNChi2);
   fChain->SetBranchAddress("electronPtRel", electronPtRel, &b_electronPtRel);
   fChain->SetBranchAddress("electronSip2d", electronSip2d, &b_electronSip2d);
   fChain->SetBranchAddress("electronIp2d", electronIp2d, &b_electronIp2d);
   fChain->SetBranchAddress("electronIpe2d", electronIpe2d, &b_electronIpe2d);
   fChain->SetBranchAddress("electronSip3d", electronSip3d, &b_electronSip3d);
   fChain->SetBranchAddress("electronIp3d", electronIp3d, &b_electronIp3d);
   fChain->SetBranchAddress("electronIpe3d", electronIpe3d, &b_electronIpe3d);
   fChain->SetBranchAddress("electronP0Par", electronP0Par, &b_electronP0Par);
   fChain->SetBranchAddress("electronDeltaR", electronDeltaR, &b_electronDeltaR);
   fChain->SetBranchAddress("electronEtaRel", electronEtaRel, &b_electronEtaRel);
   fChain->SetBranchAddress("electronRatio", electronRatio, &b_electronRatio);
   fChain->SetBranchAddress("electronTrackQuality", electronTrackQuality, &b_electronTrackQuality);
   fChain->SetBranchAddress("electronRatioRel", electronRatioRel, &b_electronRatioRel);
   fChain->SetBranchAddress("nMuons", nMuons, &b_nMuons);
   fChain->SetBranchAddress("muon1IsGlobal", muon1IsGlobal, &b_muon1IsGlobal);
   fChain->SetBranchAddress("muon1IsTracker", muon1IsTracker, &b_muon1IsTracker);
   fChain->SetBranchAddress("muon1IsStandalone", muon1IsStandalone, &b_muon1IsStandalone);
   fChain->SetBranchAddress("muon1Pt", muon1Pt, &b_muon1Pt);
   fChain->SetBranchAddress("muon1Eta", muon1Eta, &b_muon1Eta);
   fChain->SetBranchAddress("muon1Phi", muon1Phi, &b_muon1Phi);
   fChain->SetBranchAddress("muon1NumberOfMatches", muon1NumberOfMatches, &b_muon1NumberOfMatches);
   fChain->SetBranchAddress("muon1GlobalMuonHits", muon1GlobalMuonHits, &b_muon1GlobalMuonHits);
   fChain->SetBranchAddress("muon1InnerValidHits", muon1InnerValidHits, &b_muon1InnerValidHits);
   fChain->SetBranchAddress("muon1NExpectedOuterHits", muon1NExpectedOuterHits, &b_muon1NExpectedOuterHits);
   fChain->SetBranchAddress("muon1NPixelHits", muon1NPixelHits, &b_muon1NPixelHits);
   fChain->SetBranchAddress("muon1InnerNChi2", muon1InnerNChi2, &b_muon1InnerNChi2);
   fChain->SetBranchAddress("muon1GlobalNChi2", muon1GlobalNChi2, &b_muon1GlobalNChi2);
   fChain->SetBranchAddress("muon1VzPVDist", muon1VzPVDist, &b_muon1VzPVDist);
   fChain->SetBranchAddress("muon1PtRel", muon1PtRel, &b_muon1PtRel);
   fChain->SetBranchAddress("muon1Sip2d", muon1Sip2d, &b_muon1Sip2d);
   fChain->SetBranchAddress("muon1Ip2d", muon1Ip2d, &b_muon1Ip2d);
   fChain->SetBranchAddress("muon1Ipe2d", muon1Ipe2d, &b_muon1Ipe2d);
   fChain->SetBranchAddress("muon1Sip3d", muon1Sip3d, &b_muon1Sip3d);
   fChain->SetBranchAddress("muon1Ip3d", muon1Ip3d, &b_muon1Ip3d);
   fChain->SetBranchAddress("muon1Ipe3d", muon1Ipe3d, &b_muon1Ipe3d);
   fChain->SetBranchAddress("muon1P0Par", muon1P0Par, &b_muon1P0Par);
   fChain->SetBranchAddress("muon1DeltaR", muon1DeltaR, &b_muon1DeltaR);
   fChain->SetBranchAddress("muon1EtaRel", muon1EtaRel, &b_muon1EtaRel);
   fChain->SetBranchAddress("muon1Ratio", muon1Ratio, &b_muon1Ratio);
   fChain->SetBranchAddress("muon1TrackQuality", muon1TrackQuality, &b_muon1TrackQuality);
   fChain->SetBranchAddress("muon1RatioRel", muon1RatioRel, &b_muon1RatioRel);
   fChain->SetBranchAddress("muon2IsGlobal", muon2IsGlobal, &b_muon2IsGlobal);
   fChain->SetBranchAddress("muon2IsTracker", muon2IsTracker, &b_muon2IsTracker);
   fChain->SetBranchAddress("muon2IsStandalone", muon2IsStandalone, &b_muon2IsStandalone);
   fChain->SetBranchAddress("muon2Pt", muon2Pt, &b_muon2Pt);
   fChain->SetBranchAddress("muon2Eta", muon2Eta, &b_muon2Eta);
   fChain->SetBranchAddress("muon2Phi", muon2Phi, &b_muon2Phi);
   fChain->SetBranchAddress("muon2NumberOfMatches", muon2NumberOfMatches, &b_muon2NumberOfMatches);
   fChain->SetBranchAddress("muon2GlobalMuonHits", muon2GlobalMuonHits, &b_muon2GlobalMuonHits);
   fChain->SetBranchAddress("muon2InnerValidHits", muon2InnerValidHits, &b_muon2InnerValidHits);
   fChain->SetBranchAddress("muon2NExpectedOuterHits", muon2NExpectedOuterHits, &b_muon2NExpectedOuterHits);
   fChain->SetBranchAddress("muon2NPixelHits", muon2NPixelHits, &b_muon2NPixelHits);
   fChain->SetBranchAddress("muon2InnerNChi2", muon2InnerNChi2, &b_muon2InnerNChi2);
   fChain->SetBranchAddress("muon2GlobalNChi2", muon2GlobalNChi2, &b_muon2GlobalNChi2);
   fChain->SetBranchAddress("muon2VzPVDist", muon2VzPVDist, &b_muon2VzPVDist);
   fChain->SetBranchAddress("muon2PtRel", muon2PtRel, &b_muon2PtRel);
   fChain->SetBranchAddress("muon2Sip2d", muon2Sip2d, &b_muon2Sip2d);
   fChain->SetBranchAddress("muon2Ip2d", muon2Ip2d, &b_muon2Ip2d);
   fChain->SetBranchAddress("muon2Ipe2d", muon2Ipe2d, &b_muon2Ipe2d);
   fChain->SetBranchAddress("muon2Sip3d", muon2Sip3d, &b_muon2Sip3d);
   fChain->SetBranchAddress("muon2Ip3d", muon2Ip3d, &b_muon2Ip3d);
   fChain->SetBranchAddress("muon2Ipe3d", muon2Ipe3d, &b_muon2Ipe3d);
   fChain->SetBranchAddress("muon2P0Par", muon2P0Par, &b_muon2P0Par);
   fChain->SetBranchAddress("muon2DeltaR", muon2DeltaR, &b_muon2DeltaR);
   fChain->SetBranchAddress("muon2EtaRel", muon2EtaRel, &b_muon2EtaRel);
   fChain->SetBranchAddress("muon2Ratio", muon2Ratio, &b_muon2Ratio);
   fChain->SetBranchAddress("muon2TrackQuality", muon2TrackQuality, &b_muon2TrackQuality);
   fChain->SetBranchAddress("muon2RatioRel", muon2RatioRel, &b_muon2RatioRel);
   fChain->SetBranchAddress("muon3IsGlobal", muon3IsGlobal, &b_muon3IsGlobal);
   fChain->SetBranchAddress("muon3IsTracker", muon3IsTracker, &b_muon3IsTracker);
   fChain->SetBranchAddress("muon3IsStandalone", muon3IsStandalone, &b_muon3IsStandalone);
   fChain->SetBranchAddress("muon3Pt", muon3Pt, &b_muon3Pt);
   fChain->SetBranchAddress("muon3Eta", muon3Eta, &b_muon3Eta);
   fChain->SetBranchAddress("muon3Phi", muon3Phi, &b_muon3Phi);
   fChain->SetBranchAddress("muon3NumberOfMatches", muon3NumberOfMatches, &b_muon3NumberOfMatches);
   fChain->SetBranchAddress("muon3GlobalMuonHits", muon3GlobalMuonHits, &b_muon3GlobalMuonHits);
   fChain->SetBranchAddress("muon3InnerValidHits", muon3InnerValidHits, &b_muon3InnerValidHits);
   fChain->SetBranchAddress("muon3NExpectedOuterHits", muon3NExpectedOuterHits, &b_muon3NExpectedOuterHits);
   fChain->SetBranchAddress("muon3NPixelHits", muon3NPixelHits, &b_muon3NPixelHits);
   fChain->SetBranchAddress("muon3InnerNChi2", muon3InnerNChi2, &b_muon3InnerNChi2);
   fChain->SetBranchAddress("muon3GlobalNChi2", muon3GlobalNChi2, &b_muon3GlobalNChi2);
   fChain->SetBranchAddress("muon3VzPVDist", muon3VzPVDist, &b_muon3VzPVDist);
   fChain->SetBranchAddress("muon3PtRel", muon3PtRel, &b_muon3PtRel);
   fChain->SetBranchAddress("muon3Sip2d", muon3Sip2d, &b_muon3Sip2d);
   fChain->SetBranchAddress("muon3Ip2d", muon3Ip2d, &b_muon3Ip2d);
   fChain->SetBranchAddress("muon3Ipe2d", muon3Ipe2d, &b_muon3Ipe2d);
   fChain->SetBranchAddress("muon3Sip3d", muon3Sip3d, &b_muon3Sip3d);
   fChain->SetBranchAddress("muon3Ip3d", muon3Ip3d, &b_muon3Ip3d);
   fChain->SetBranchAddress("muon3Ipe3d", muon3Ipe3d, &b_muon3Ipe3d);
   fChain->SetBranchAddress("muon3P0Par", muon3P0Par, &b_muon3P0Par);
   fChain->SetBranchAddress("muon3DeltaR", muon3DeltaR, &b_muon3DeltaR);
   fChain->SetBranchAddress("muon3EtaRel", muon3EtaRel, &b_muon3EtaRel);
   fChain->SetBranchAddress("muon3Ratio", muon3Ratio, &b_muon3Ratio);
   fChain->SetBranchAddress("muon3TrackQuality", muon3TrackQuality, &b_muon3TrackQuality);
   fChain->SetBranchAddress("muon3RatioRel", muon3RatioRel, &b_muon3RatioRel);
   fChain->SetBranchAddress("muon4IsGlobal", muon4IsGlobal, &b_muon4IsGlobal);
   fChain->SetBranchAddress("muon4IsTracker", muon4IsTracker, &b_muon4IsTracker);
   fChain->SetBranchAddress("muon4IsStandalone", muon4IsStandalone, &b_muon4IsStandalone);
   fChain->SetBranchAddress("muon4Pt", muon4Pt, &b_muon4Pt);
   fChain->SetBranchAddress("muon4Eta", muon4Eta, &b_muon4Eta);
   fChain->SetBranchAddress("muon4Phi", muon4Phi, &b_muon4Phi);
   fChain->SetBranchAddress("muon4NumberOfMatches", muon4NumberOfMatches, &b_muon4NumberOfMatches);
   fChain->SetBranchAddress("muon4GlobalMuonHits", muon4GlobalMuonHits, &b_muon4GlobalMuonHits);
   fChain->SetBranchAddress("muon4InnerValidHits", muon4InnerValidHits, &b_muon4InnerValidHits);
   fChain->SetBranchAddress("muon4NExpectedOuterHits", muon4NExpectedOuterHits, &b_muon4NExpectedOuterHits);
   fChain->SetBranchAddress("muon4NPixelHits", muon4NPixelHits, &b_muon4NPixelHits);
   fChain->SetBranchAddress("muon4InnerNChi2", muon4InnerNChi2, &b_muon4InnerNChi2);
   fChain->SetBranchAddress("muon4GlobalNChi2", muon4GlobalNChi2, &b_muon4GlobalNChi2);
   fChain->SetBranchAddress("muon4VzPVDist", muon4VzPVDist, &b_muon4VzPVDist);
   fChain->SetBranchAddress("muon4PtRel", muon4PtRel, &b_muon4PtRel);
   fChain->SetBranchAddress("muon4Sip2d", muon4Sip2d, &b_muon4Sip2d);
   fChain->SetBranchAddress("muon4Ip2d", muon4Ip2d, &b_muon4Ip2d);
   fChain->SetBranchAddress("muon4Ipe2d", muon4Ipe2d, &b_muon4Ipe2d);
   fChain->SetBranchAddress("muon4Sip3d", muon4Sip3d, &b_muon4Sip3d);
   fChain->SetBranchAddress("muon4Ip3d", muon4Ip3d, &b_muon4Ip3d);
   fChain->SetBranchAddress("muon4Ipe3d", muon4Ipe3d, &b_muon4Ipe3d);
   fChain->SetBranchAddress("muon4P0Par", muon4P0Par, &b_muon4P0Par);
   fChain->SetBranchAddress("muon4DeltaR", muon4DeltaR, &b_muon4DeltaR);
   fChain->SetBranchAddress("muon4EtaRel", muon4EtaRel, &b_muon4EtaRel);
   fChain->SetBranchAddress("muon4Ratio", muon4Ratio, &b_muon4Ratio);
   fChain->SetBranchAddress("muon4TrackQuality", muon4TrackQuality, &b_muon4TrackQuality);
   fChain->SetBranchAddress("muon4RatioRel", muon4RatioRel, &b_muon4RatioRel);
   fChain->SetBranchAddress("standardCombinedSecondaryVertexMVAPFBJetTags", standardCombinedSecondaryVertexMVAPFBJetTags, &b_standardCombinedSecondaryVertexMVAPFBJetTags);
   fChain->SetBranchAddress("standardCombinedSecondaryVertexPFBJetTags", standardCombinedSecondaryVertexPFBJetTags, &b_standardCombinedSecondaryVertexPFBJetTags);
   fChain->SetBranchAddress("standardGhostTrackPFBJetTags", standardGhostTrackPFBJetTags, &b_standardGhostTrackPFBJetTags);
   fChain->SetBranchAddress("standardJetBProbabilityPFBJetTags", standardJetBProbabilityPFBJetTags, &b_standardJetBProbabilityPFBJetTags);
   fChain->SetBranchAddress("standardJetProbabilityPFBJetTags", standardJetProbabilityPFBJetTags, &b_standardJetProbabilityPFBJetTags);
   fChain->SetBranchAddress("standardSimpleSecondaryVertexHighEffPFBJetTags", standardSimpleSecondaryVertexHighEffPFBJetTags, &b_standardSimpleSecondaryVertexHighEffPFBJetTags);
   fChain->SetBranchAddress("standardSimpleSecondaryVertexHighPurPFBJetTags", standardSimpleSecondaryVertexHighPurPFBJetTags, &b_standardSimpleSecondaryVertexHighPurPFBJetTags);
   fChain->SetBranchAddress("standardSoftElectronByIP3dPFBJetTags", standardSoftElectronByIP3dPFBJetTags, &b_standardSoftElectronByIP3dPFBJetTags);
   fChain->SetBranchAddress("standardSoftElectronByPtPFBJetTags", standardSoftElectronByPtPFBJetTags, &b_standardSoftElectronByPtPFBJetTags);
   fChain->SetBranchAddress("standardSoftMuonByIP3dPFBJetTags", standardSoftMuonByIP3dPFBJetTags, &b_standardSoftMuonByIP3dPFBJetTags);
   fChain->SetBranchAddress("standardSoftMuonByPtPFBJetTags", standardSoftMuonByPtPFBJetTags, &b_standardSoftMuonByPtPFBJetTags);
   fChain->SetBranchAddress("standardSoftMuonPFBJetTags", standardSoftMuonPFBJetTags, &b_standardSoftMuonPFBJetTags);
   fChain->SetBranchAddress("standardTrackCountingHighEffPFBJetTags", standardTrackCountingHighEffPFBJetTags, &b_standardTrackCountingHighEffPFBJetTags);
   fChain->SetBranchAddress("standardTrackCountingHighPurPFBJetTags", standardTrackCountingHighPurPFBJetTags, &b_standardTrackCountingHighPurPFBJetTags);
}

Bool_t MuonSelector::Notify()
{
   // The Notify() function is called when a new file is opened. This
   // can be either for a new TTree in a TChain or when when a new TTree
   // is started when using PROOF. It is normally not necessary to make changes
   // to the generated code, but the routine can be extended by the
   // user if needed. The return value is currently not used.

   return kTRUE;
}

#endif // #ifdef MuonSelector_cxx
